#
# Build automated test environment
#
parameters:
  poolName: 'windows-2019'
  rgName: 'automated-test-rg-1'
  location: 'eastus'

jobs:
  - job: Build_environment
    displayName: Build testing environment
    pool:
      vmImage: ${{ parameters.poolName }}
    steps:
    - task: AzurePowerShell@4
      inputs:
        azureSubscription: 'AzureIndustrialIot-conn'
        ScriptType: 'FilePath'
        ScriptPath: 'tools/scripts/deploy.ps1'
        scriptArguments:
          -type test `
          -resourceGroupName ${{ parameters.rgName }} `
          -resourceGroupLocation ${{ parameters.location }} `
          -subscriptionId $(subscription_id) `
          -applicationName ${{ parameters.rgName }} `
          -aadClientId $(client_id) `
          -aadClientSecret $(client_secret) `
          -aadTenantIdForTestEnv $(tenant_id)
        azurePowerShellVersion: 'LatestVersion'
